### ISSUE TITLE
InfluxDB Pandas example: client.delete_database(dbname) error

### ISSUE THREAD

**Issue by ajsmith007** [influxdata/influxdb-python#358]
The pandas example has a bug in the following code around line 32:

```
print("Delete database: " + dbname)
    client.delete_database(dbname)
```

which returns

```
Traceback (most recent call last):
  File "/Users/drew/PycharmProjects/influxdb/influxdb_pandas.py", line 52, in <module>
    main(host=args.host, port=args.port)
  File "/Users/drew/PycharmProjects/influxdb/influxdb_pandas.py", line 36, in main
    client.delete_database(dbname)
AttributeError: 'DataFrameClient' object has no attribute 'delete_database'
```

and should be:

```
print("Delete database: " + dbname)
    client.drop_database(dbname)
```

**Comment by gseismic** [comment]
Yes

**Comment by gansanay** [comment]
Addressed in PR #386

**Comment by gsokoll** [comment]
Issue still exists in influxdb-python/examples/tutorial_pandas.py

line 32: client.delete_database(dbname)
